### ISSUE TITLE
Go package showing up

### ISSUE THREAD

**Issue by jwoertink** [shardbox/catalog#54]
I'm not sure if this is the right repo to post this issue, but I saw this https://shardbox.org/shards/html-pipeline 

I don't see any Crystal code, so I'm not sure how this was added. Maybe it used to be, but was rewritten?

**Comment by jwoertink** [comment]
oh, looks like there is a crystal version https://github.com/huacnlee/html-pipeline.cr It's just a different repo.

**Comment by straight-shoota** [comment]
Thanks. It's probably just a typo and easy to fix. 

It's odd though, that `huacnlee/html-pipeline` shows up at all. It appears this repo has no `shard.yml` in any tagged version, so it shouldn't be picked up. I'll look into that.

**Comment by straight-shoota** [comment]
Fixed in fd4749d2207b2acdb0cd690a86d711e8513d568e
