### ISSUE TITLE
Shard labeled incorrectly

### ISSUE THREAD

**Issue by jwoertink** [shardbox/catalog#68]
https://shardbox.org/shards/amber_router~luckyframework

I tried finding this to see if I could change it, but I'm not sure where it's pulling this from. It says "amber_router", but it's obviously the lucky router :joy:

**Comment by straight-shoota** [comment]
Yeah the project name is set the first time a repository gets visited and is not expected to change or be changeable.

IIRC, the router shard's repo was originally at https://github.com/luckyframework/lucky_router and later moved to https://github.com/luckyframework/router, right?

Maybe at this URL there was previously a copy of the amber router? Then shardbox might have picked that up.

**Comment by straight-shoota** [comment]
There is also https://shardbox.org/shards/lucky_router which is the correct shard name but only has the former repo URL attached. So we probably just need to merge both entries into one, with the old URL as a legacy URL.

**Comment by straight-shoota** [comment]
#69 should fix this. I might have to manually edit the shard name afterwards, because it should pick the one from the entry that has the now canonical repo associated, which is [amber_router~luckyframework](https://shardbox.org/shards/amber_router~luckyframework).

**Comment by jwoertink** [comment]
Ah interesting. Cool, thanks for looking at that :+1:

**Comment by straight-shoota** [comment]
Should be correct now: https://shardbox.org/shards/lucky_router

**Comment by jwoertink** [comment]
Yup! Looks good. Thanks :smile:
